### ISSUE TITLE
Request for inclusion of the following ontology terms

### ISSUE THREAD

**Issue by NukP** [BIG-MAP/BattINFO#109]
Dear BattInfo moderators, 
I am Nukorn Plainpan, a postdoc working at Materials for Energy Conversion lab at Empa under Prof. Dr. Corsin Battaglia. We are part of the battery 2030 consortium and are now working on ontologizing out metadata schemas for our battery experiment using BattInfo ontology. While trying to ontologize our metadata schemas, we ran into the following terms which we would like to use in our metadata schemas but is not yet existed in BattInfo. I have also provided the suggested elucidation for the requested terms and the example of the metadata from our schemas that requires the requested term. Please find the terms in the table below. We are open to discussion. Please let either me or Corsin know should you wish to discuss this matter. Thank you. 

| **Requested term** 	| **Proposed meaning** 	| **Example of metadata terms that requires the requested term** 	|
|:---:	|:---:	|:---:	|
| AverageParticleSize 	| The mean dimension of particles in a sample 	| Cathode active material average particle size 	|
| Diameter 	| Linear dimension across a circular or spherical component, significant in electrode particle sizing and cell design. 	| Cathode diameter / Separator diamter 	|
| Porosity 	| Ratio of void volume to total volume in a material 	| Cathode porosity 	|
| PracticalCapacity 	| Usable energy storage capacity of a battery under operational conditions, lower than theoretical capacity due to real-world inefficiencies. 	| Anode practical capacity 	|
| Provenance 	| Origin or source of battery materials 	| Cathode active material provenance 	|
| Thickness 	| Physical dimension of a layer within a battery 	| Cathode active material coating thickness 	|
| Tortuosity 	| Measure of path complexity for ion transport in porous structures 	| Cathode tortuosity 	|
| ElectrolyteSalt 	| Ionic compound in an electrolyte solution facilitating ion transport 	| Electrolyte salt concentration 	|
| Concentration 	| Amount of a substance per defined volume or mass in a solution 	| Electrolyte salt concentration 	|
| Solvent 	| Liquid medium in which electrolyte components are dissolved 	| Electrolyte solvent ratio 	|
| Ratio 	| Proportion of components in a mixture 	| Electrolyte solvent ratio 	|
| ElectrolyteAdditive 	| Chemicals added to enhance electrolyte performance 	| Electrolyte additive type 	|
| hasType 	| A connector connecting an object with its different variation.  	| Electrolyte additive type 	|

**Comment by jsimonclark** [comment]
Hi Nukorn, 

thanks very much for your suggestions and engagement with BattINFO! Let's go through your list point-by-point

| Requested Term | Response | 
|-----------------|-----------------|
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| Diameter | This exists already in EMMO with the ID [EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6](http://emmo.info/emmo#EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6) | [EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9](http://emmo.info/emmo#EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9)
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 |

**Comment by jsimonclark** [comment]
Hi Nukorn, 

thanks very much for your suggestions and engagement with BattINFO! Let's go through your list point-by-point 

| Requested Term | Response | 
|-----------------|-----------------|
| AverageParticleSize | This might be covered already by the term ParticleSizeD50 | 
| Diameter | This exists already in EMMO with the ID [EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6](http://emmo.info/emmo#EMMO_c1c8ac3c_8a1c_4777_8e0b_14c1f9f9b0c6) | 
| Porosity| This exists already in EMMO with the ID [EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9](http://emmo.info/emmo#EMMO_3a6578ac_aee0_43b9_9bc6_1eb208c8c9a9) | 
| PracticalCapacity | This gets tricky because making "Practical" quantities can blow up the size of the ontology. Is practical capacity a regulated term, i.e. covered under some standards from ISO / IEC / ANSI or guidelines like IUPAC? If so, please provide the ID. Otherwise, recommendation is to use dual typing with Capacity and ConventionalQuantity or MeasuredQuantity. This can be opened as its own issue if it requires further discussion. | 
| Provenance| For this, I would recommend to use either schema.org terms (e.g. schema:manufacturer) or PROV-O terms, depending on the intention | 
| Thickness| This exists already in EMMO with the ID [EMMO_43003c86_9d15_433b_9789_ee2940920656](http://emmo.info/emmo#EMMO_43003c86_9d15_433b_9789_ee2940920656) | 
| ElectrolyteSalt | This exists already in the chemical substance domain as Salt. Will be included in BattINFO in the next update. | 
| Concentration| This exists already in EMMO as AmountConcentration under the ID [EMMO_d5be1faf_0c56_4f5a_9b78_581e6dee949f](http://emmo.info/emmo#EMMO_d5be1faf_0c56_4f5a_9b78_581e6dee949f) | 
| Solvent | This exists already in the chemical substance domain as SolventCompound. Will be incuded in BattINFO in the next update | 
| Ratio| This is included already in EMMO as RatioQuantity [EMMO_faab3f84_e475_4a46_af9c_7d249f0b9aef](http://emmo.info/emmo#EMMO_faab3f84_e475_4a46_af9c_7d249f0b9aef) | 
| ElectrolyteAdditive | We have had some discussions on whether this is a necessary term or not. From a semantic perspective, the meaning is a bit wobbly because what about cases where a compound is both an additive and a solvent (e.g. FEC)? But in general, I think this is such a widely used term in the domain that it needs to be included in some fashion. I will make a proposal for it in the next update. | 
| hasType | In general, this can be done with subclassing...or can you provide a more specific example of what you have in mind? |

**Comment by NukP** [comment]
Hi Simon, thank you for your respond. It is very helpful. I have the following respond to your suggestion: 

| **Metadata   term** |          **Action**         |                                                                                                                                                                                                                                                                                                                          **Notes**                                                                                                                                                                                                                                                                                                                         |
|:-------------------:|:---------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| AverageParticleSize | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Diameter            | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Porosity            | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| PracticalCapacity   | Not resolved                | Practical capacity thing:      Corsin agreed to repalce 'Practical capacity' with 'Measured capacity' and   I will be using the link as you suggested. However, with 'Measured capacity'   Corsin also would like to also imply how this was measured: (half/full   cell,      upper cut-off voltage, C-rate, temperature, …). I am not quite sure how to   implement this. May be having another row something like Method of   measurement where the user will have to specify how the measurement of the   capacity was done. What do you think about this? and if so, is there an   ontology to describe this new row: 'Method of measuring capacity'? |
| Provenance          | Resolved                    | I will be using https://schema.org/manufacturer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Thickness           | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Tortuosity          | Not resolved                | You forget to mention this previous respond                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ElectrolyteSalt     | Not resolved                | So should I use the one in chemical substance or should I wait for the   implementation in the next BattINFO update?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Concentration       | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Solvent             | Not resolved                | So should I use the one in chemical substance or should I wait for the   implementation in the next BattINFO update?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| Ratio               | Resolved                    | Accepted the suggested term                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ElectrolyteAdditive | Waiting for the next update | Can you provide me with an approximate on when this will be implemented?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| hasType             | Not resolved                | I want to use this connector for   type of item in general. For example:            Cathode binder type, My current intended link is:   Battery-hasPart-Cathode-hasPart-Binder-hasType            Cathode current collector,  My   current intended link is:   Battery-hasPart-Cathode-hasPart-CurrentCollector-hasType            Please advice me on what I should use.                                                                                                                                                                                                                                                                                  |

On top of this, I also note that With some links with words electrochemistry in the url (e.g. [http://emmo.info/electrochemistry](http://emmo.info/electrochemistry%EF%BF%BC)[#electrochemistry_35c650ab_3b23_4938_b312_1b0dede2e6d5)](http://emmo.info/electrochemistry%EF%BF%BC)[,](http://emmo.info/electrochemistry%EF%BF%BC) when I clicked on it, I got redirected to thee definition of such term. For EMMO link that you provided, (e.g. [http://emmo.info/emmo](http://emmo.info/emmo%EF%BF%BC)[#EMMO_7efd64d1_05a1_49cd_a7f0_783ca050d4f3](http://emmo.info/emmo%EF%BF%BC) ) I got redirected to the same page that desribe the EMMO ontology in general, but not the term themself. Is this ok, or is the link is broken?

**Comment by jsimonclark** [comment]
| Metadata Term | Response | 
|-----------------|-----------------|
| PracticalCapacity | I'll create a dedicated issue for this one, since it will take a little more in-depth discussion to resolve. |
| Tortuosity | Thank you. Tortuosity is: https://w3id.org/emmo#EMMO_c413d96f_c57b_4c70_9ac1_312db6c009a8 |
| ElectrolyteSalt | BattINFO imports the chemical substance domain, so it is fine to use the IRIs from there |
| Solvent | Same as above - it's fine to use terms from chemical substance |
| ElectrolyteAdditive | I'll add it within the next week (2024-03-08) |
| hasType | I'll also create a dedicated issue for this one, since it would make a nice usage example |

Regarding the links - we are in the process of migrating to the w3id.org PURL (permanent uniform resource locator) namespace. PURLs are helpful because they offer a permanent way of pointing to things on the web, so that even if the place where the information is hosted changes sometime in the future, the PURL will always be correct. That migration should be complete within the next week or so. 

As you can see, the "old" IRIs will still work: http://emmo.info/electrochemistry#electrochemistry_35c650ab_3b23_4938_b312_1b0dede2e6d5
But the w3id.org is what we prefer going foward: https://w3id.org/emmo/domain/electrochemistry#electrochemistry_35c650ab_3b23_4938_b312_1b0dede2e6d5

I've asked the EMMO core developers to update their re-direct rules such that the IRI will point to the documentation for the term (in the same way that BattINFO domains do). I hope they can get that implemented soon (i.e. within the next few weeks).

**Comment by jsimonclark** [comment]
ElectrolyteAdditive has been added (https://w3id.org/emmo/domain/electrochemistry#electrochemistry_554286d4_1f46_44c0_bebc_4ddae00dbce1) 

I'm going to close this issue and we can continue the discussion on dedicated issues as needed.

**Comment by NukP** [comment]
@jsimonclark ok, thank you for adding new terms. I will conatct you if I need further discussion.
